ACCENTURE/Progetto/red-main/RedWeb/src/it/ibm/red/web/ricerca/mbean/RicercaAbstractBean.java
package it.ibm.red.web.ricerca.mbean;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.faces.component.UIColumn;

import it.ibm.red.business.dto.UtenteDTO;
import it.ibm.red.business.enums.PropertiesNameEnum;
import it.ibm.red.business.provider.ApplicationContextProvider;
import it.ibm.red.business.service.facade.IPropertiesFacadeSRV;
import it.ibm.red.business.utils.StringUtils;
import it.ibm.red.web.constants.ConstantsWeb;
import it.ibm.red.web.enums.DettaglioDocumentoFileEnum;
import it.ibm.red.web.helper.faces.FacesHelper;
import it.ibm.red.web.mbean.AbstractBean;
import it.ibm.red.web.mbean.SessionBean;
import it.ibm.red.web.utils.ExportUtils;

/**
 * Abstract Bean della ricerca.
 * @param <M>
 */
public abstract class RicercaAbstractBean<M> extends AbstractBean {
	
	/**
	 * Costante serial version UID.
	 */
	private static final long serialVersionUID = 8735231145923157885L;
	
	/**
	 * File principale.
	 */
	protected static final String FILE_PRINCIPALE = "File principale: ";
	
	/**
	 * Messaggio informativo per il raggiungimento del massimo numero di risultati.
	 */
	public static final String MSG_NUM_MAX_RISULTATI = "La ricerca ha raggiunto il numero massimo di elementi visualizzabili." 
			+ " Inserire ulteriori filtri di ricerca per ridurre il numero dei risultati.";
	
	/**
	 *  Numero di caratteri a cui troncare la stringa 
	 */
	private static final int TRUNCATE_SIZE = 60;

	/**
	 * Bean di sessione.
	 */
	protected SessionBean sessionBean;

	/**
	 * Utente.
	 */
	protected UtenteDTO utente;
	
	/**
	 * Numero massimo di risultati della ricerca.
	 */
	private Integer numMaxRisultati;
	
	/**
	 * Dettaglio documento.
	 */
	private DettaglioDocumentoFileEnum dettaglioDaCaricare;
	
	/**
	 * Post construct del bean.
	 */
	@Override
	protected void postConstruct() {
		sessionBean = FacesHelper.getManagedBean(ConstantsWeb.MBean.SESSION_BEAN);
		utente = sessionBean.getUtente();
		
		dettaglioDaCaricare = DettaglioDocumentoFileEnum.GENERICO;
		
		final IPropertiesFacadeSRV propertiesSRV = ApplicationContextProvider.getApplicationContext().getBean(IPropertiesFacadeSRV.class);
		numMaxRisultati = Integer.parseInt(propertiesSRV.getByEnum(PropertiesNameEnum.RICERCA_MAX_RESULTS));
	}
	
	/**
	 * Restituisce il documento attualmente selezionato dall'utente o sul quale si desidera eseguire una operazione.
	 */
	protected abstract M getSelectedDocument();

	/**
	 * Gestisce la selezione del edttaglipartire dal master della ricerca.
	 * 
	 * @param m
	 */
	protected abstract void selectDetail(M m);
	
	/**
	 * Metodo per recuperare il valore corretto da esportare per la colonna 'descrizione' 
	 * @param column
	 * @return
	 */
	public String columnDescrizione(final UIColumn column) {
       return ExportUtils.columnCorrectValue(column);
    }
	
	/** 
	 * Abbrevia il label presente in una colonna di un datatable con i puntini.
	 * Inserire il label intero con i puntini utilizzanfo l'apposito metodo getColumnTooltip
	 * 
	 * Gestisce il caso label vuoto restituisce il classico  " - "
	 * 
 	 * @param columnLabel
	 * 	Stringa da visualizzare nella colonna
	 * @param size
	 * 	massimo numero di caratteri del label che si vogliono visualizzare
	 *  
	 * @return la stringa columnLabel se maggiore di size troncata di size e aggiungendo i punti '...' alla fine
	 * se columnLabel è null ritorna " - "
	 * 
	 */
	@Override
	public String getShortColumn(final String columnLabel, final Integer size) {
		return StringUtils.truncateColumnTable(columnLabel, size);
	}
	
	/**
	 * Restituisce la label della colonna abbreviata.
	 */
	@Override
	public String getShortColumn(final String columnLabel) {
		return StringUtils.truncateColumnTable(columnLabel, TRUNCATE_SIZE);
	}
	
	/**
	 * Restituisce il nome del file per l'export della coda.
	 * @return nome file per export
	 */
	public String getNomeFileExportCoda() {
		String nome = "";
		if (sessionBean.getUtente() != null) {
			nome += sessionBean.getUtente().getNome().toLowerCase() + "_" + sessionBean.getUtente().getCognome().toLowerCase() + "_";
		}
		
		nome += getNomeRicerca4Excel() + "_";
		
		final SimpleDateFormat sdf = new SimpleDateFormat("dd_MM_yyyy_HH.mm");
		nome += sdf.format(new Date()); 
		
		return nome;
	}
	
	/**
	 * Restituisce una parte della stringa del file Excel per l'export dei risultati di ricerca.
	 * @return nome file excel per export
	 */
	protected abstract String getNomeRicerca4Excel();

	/**
	 * Restituisce il dettaglio da caricare.
	 * @return dettaglio da caricare
	 */
	public DettaglioDocumentoFileEnum getDettaglioDaCaricare() {
		return dettaglioDaCaricare;
	}

	/**
	 * Restituisce il numero massimo dei risultati.
	 * @return numero massimo risultati
	 */
	public Integer getNumMaxRisultati() {
		return numMaxRisultati;
	}

	/**
	 * Imposta il numero massimo dei risultati.
	 * @param numMaxRisultati
	 */
	public void setNumMaxRisultati(final Integer numMaxRisultati) {
		this.numMaxRisultati = numMaxRisultati;
	}

}

ACCENTURE/Progetto/red-main/RedWeb/src/it/ibm/red/web/ricerca/mbean/RicercaAnnullaProcedimentoBean.java
package it.ibm.red.web.ricerca.mbean;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import it.ibm.red.business.dto.EsitoOperazioneDTO;
import it.ibm.red.business.dto.MasterDocumentRedDTO;
import it.ibm.red.business.dto.UtenteDTO;
import it.ibm.red.business.enums.TipologiaProtocollazioneEnum;
import it.ibm.red.business.logger.REDLogger;
import it.ibm.red.business.provider.ApplicationContextProvider;
import it.ibm.red.business.service.facade.IASignFacadeSRV;
import it.ibm.red.business.service.facade.IDocumentoRedFacadeSRV;
import it.ibm.red.web.constants.ConstantsWeb;
import it.ibm.red.web.helper.faces.FacesHelper;
import it.ibm.red.web.mbean.AbstractBean;
import it.ibm.red.web.mbean.SessionBean;

/**
 * Bean che gestisce la funzionalità della ricerca dei procedimenti annullati.
 */
@RequestScoped
@Named(ConstantsWeb.MBean.RICERCA_ANNULLA_PROCEDIMENTO_BEAN)
public class RicercaAnnullaProcedimentoBean extends AbstractBean {

	/**
	 * Costante serial version UID.
	 */
	private static final long serialVersionUID = 1561924608515666735L;
	
	/**
	 * Logger.
	 */
	private static final REDLogger LOGGER = REDLogger.getLogger(RicercaAnnullaProcedimentoBean.class);
	
	/**
	 * Bean di ricerca.
	 */
	private RicercaDocumentiRedAbstractBean ricerca;

	/**
	 * Motivazione.
	 */
	private String motivazione;

	/**
	 * Provvedimento.
	 */
	private String provvedimento;

	/**
	 * Flag registrato.
	 */
	private boolean registred = false;

	/**
	 * Flag nps.
	 */
	private boolean beforeWasNps = false;
	
	@Override
	protected void postConstruct() {
		// Metodo intenzionalmente vuoto.
	}
	
	/**
	 * Esegue la logica di annullamento del procedimento.
	 */
	public void registra() {
		final SessionBean sessionBean = FacesHelper.getManagedBean(ConstantsWeb.MBean.SESSION_BEAN);
		final UtenteDTO utente = sessionBean.getUtente();
		final MasterDocumentRedDTO currentMaster = ricerca.getSelectedDocument();
		EsitoOperazioneDTO esito = null; 
		
		final IASignFacadeSRV asyncSignSRV = ApplicationContextProvider.getApplicationContext().getBean(IASignFacadeSRV.class);
		try {
			if(Boolean.TRUE.equals(asyncSignSRV.isPresent(currentMaster.getDocumentTitle()))) {
				showWarnMessage("Impossibile annullare il documento poiché in fase di invio in firma.");
				return;
			}
			IDocumentoRedFacadeSRV documentoRedSRV = ApplicationContextProvider.getApplicationContext().getBean(IDocumentoRedFacadeSRV.class);
			esito = documentoRedSRV.annullaDocumentoOAnnullaProtocollo(currentMaster.getDocumentTitle(), motivazione, provvedimento, utente);
			
			if (esito.isEsito()) {
				showInfoMessage("Annullamento del documento effettuato correttamente.");
				EsitoOperazioneDTO esitoRiattiva = documentoRedSRV.riattivaDocIngressoAfterChiusuraRisposta(currentMaster.getDocumentTitle(), utente);
				if(esitoRiattiva!=null){
					if(esitoRiattiva.isEsito()) {
						showInfoMessage("Riattivazione del doc ingresso associato avvenuta correttamente");
					} else {
						showError(esitoRiattiva.getNote());
					}
				}
			} else {
				showError(esito.getNote());
			}
		} catch (Exception e) {
			String msg = "Impossibile annullare il documento.";
			
			if(esito != null) {
				msg = esito.getNote();
			}
			
			LOGGER.error(msg, e);
			showError(msg);
			
		} finally {
			//update content
			ricerca.selectDetail(currentMaster);
			registred = true;
		}
	}
	
	/**
	 * Gestisce la chiusura.
	 */
	public void close() {
		setMotivazione(null);
		setProvvedimento(null);
		beforeWasNps = false;
		registred = false;
	}
	
	/**
	 * Verifica che il tipo di procedimento sia NPS.
	 * @return true se tipo procedimento è NPS, false altrimenti.
	 */
	public boolean isTipoProcedimentoNps() {
		final MasterDocumentRedDTO currentMaster = ricerca.getSelectedDocument();
		
		final SessionBean sessionBean = FacesHelper.getManagedBean(ConstantsWeb.MBean.SESSION_BEAN);
		final UtenteDTO utente = sessionBean.getUtente();
		if (!registred) {
			beforeWasNps = false;
			if (currentMaster != null) {
				beforeWasNps = utente !=  null 
						&& TipologiaProtocollazioneEnum.isProtocolloNPS(utente.getIdTipoProtocollo())
						//Verifichiamo che il documento sia NPS 
						&& currentMaster.getOggettoProtocolloNPS() != null 
						&& currentMaster.getOggettoProtocolloNPS().length() > 0;
			}
		}
		return beforeWasNps;
	}

	/**
	 * Restituisce la motivazione.
	 * @return motivazione
	 */
	public String getMotivazione() {
		return motivazione;
	}

	/**
	 * Imposta la motivazione.
	 * @param motivazione
	 */
	public void setMotivazione(final String motivazione) {
		this.motivazione = motivazione;
	}

	/**
	 * Restituisce il provvedimento.
	 * @return provvedimento
	 */
	public String getProvvedimento() {
		return provvedimento;
	}

	/**
	 * Imposta il provvedimento.
	 * @param provvedimento
	 */
	public void setProvvedimento(final String provvedimento) {
		this.provvedimento = provvedimento;
	}

	/**
	 * Imposta la ricerca.
	 * @param ricerca
	 */
	public void setRicerca(final RicercaDocumentiRedAbstractBean ricerca) {
		this.ricerca = ricerca;
	}
	
}

ACCENTURE/Progetto/red-main/RedWeb/src/it/ibm/red/web/ricerca/mbean/RicercaContiConsuntiviBean.java
package it.ibm.red.web.ricerca.mbean;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import com.google.common.net.MediaType;

import it.ibm.red.business.dto.ParamsRicercaContiConsuntiviDTO;
import it.ibm.red.business.dto.RisultatoRicercaContiConsuntiviDTO;
import it.ibm.red.business.dto.SelectItemDTO;
import it.ibm.red.business.dto.StatoRicercaDTO;
import it.ibm.red.business.enums.ContiConsuntiviEnum;
import it.ibm.red.business.logger.REDLogger;
import it.ibm.red.business.provider.ApplicationContextProvider;
import it.ibm.red.business.service.IContiConsuntiviFacadeSRV;
import it.ibm.red.business.service.facade.ITipologiaDocumentoFacadeSRV;
import it.ibm.red.web.constants.ConstantsWeb;
import it.ibm.red.web.helper.faces.FacesHelper;
import it.ibm.red.web.mbean.AbstractBean;
import it.ibm.red.web.mbean.SessionBean;

/**
 * Bean che gestisca la ricerca per conti consuntivi.
 */
@Named(ConstantsWeb.MBean.RICERCA_CONTI_CONSUNTIVI_BEAN)
@ViewScoped
public class RicercaContiConsuntiviBean extends AbstractBean {
	
	/**
	 * serial version UID.
	 */
	private static final long serialVersionUID = -8659886620858883202L;

	/**
	 * Logger.
	 */
	private static final REDLogger LOGGER = REDLogger.getLogger(RicercaContiConsuntiviBean.class.getName());
	
	/**
	 * Session Bean.
	 */
	private SessionBean sessionBean;
	
	/**
	 * Service per la generazione del pdf.
	 */
	private IContiConsuntiviFacadeSRV contiConsuntiviSRV;

	/**
	 * Form di ricerca elenco notifiche e conti consuntivi.
	 */
	private ParamsRicercaContiConsuntiviDTO formContiConsuntivi;
	
	/**
	 * Risultato.
	 */
	private StatoRicercaDTO result;
	
	/**
	 * Lista delle sedi estere.
	 */
	private List<SelectItemDTO> sediEstere;
	
	/**
	 * Post construct del bean.
	 */
	@Override
	@PostConstruct
	protected void postConstruct() {
		setResult((StatoRicercaDTO) FacesHelper.getObjectFromSession(ConstantsWeb.SessionObject.RISULTATO_RICERCA_CONTI_CONSUNTIVI, true));
		sessionBean = FacesHelper.getManagedBean(ConstantsWeb.MBean.SESSION_BEAN);
		ITipologiaDocumentoFacadeSRV tipologiaDocumentoSRV = ApplicationContextProvider.getApplicationContext().getBean(ITipologiaDocumentoFacadeSRV.class);
		contiConsuntiviSRV = ApplicationContextProvider.getApplicationContext().getBean(IContiConsuntiviFacadeSRV.class);
		
		if(result != null) {
			formContiConsuntivi = (ParamsRicercaContiConsuntiviDTO) result.getFormRicerca();
		}
		
		sediEstere = tipologiaDocumentoSRV.getValuesBySelector(ContiConsuntiviEnum.ANAGSEDEST.getMetadatoName(), null, sessionBean.getUtente().getIdAoo());
	}
	
	/**
	 * Metodo per reimpostare nel session bean il form di ricerca.
	 */
	public void ripetiRicercaContiConsuntiviUcb() {
		try {
			sessionBean.getRicercaFormContainer().setContiConsuntiviUCB(formContiConsuntivi);
		} catch (final Exception e) {
			LOGGER.error(e);
			showError(e);
		}
	}
	
	/**
	 * Restituisce il nome del file per l'export della coda.
	 * 
	 * @return nome file per export
	 */
	public String getNomeFileExport() {
		String nome = "";
		if (sessionBean.getUtente() != null) {
			nome += sessionBean.getUtente().getNome().toLowerCase() + "_" + sessionBean.getUtente().getCognome().toLowerCase() + "_";
		}
		
		nome += "report_elenco_notifiche_conti_consuntivi_";
		
		final SimpleDateFormat sdf = new SimpleDateFormat("dd_MM_yyyy_HH.mm");
		nome += sdf.format(new Date()); 
		
		return nome;
	}
	
	/**
	 * Restituisce lo streamed content.
	 */
	public StreamedContent downloadPdf() {
		StreamedContent sc = null;
		final String exportString = getNomeFileExport() + ".pdf";
		List<RisultatoRicercaContiConsuntiviDTO> risultatiContiConsuntivi = (List<RisultatoRicercaContiConsuntiviDTO>) result.getRisultatiRicerca();
		try {
			// recupero del content
			final InputStream stream = new ByteArrayInputStream(contiConsuntiviSRV.generaPdfReport(formContiConsuntivi, risultatiContiConsuntivi, sessionBean.getUtente()));
			sc = new DefaultStreamedContent(stream, MediaType.PDF.toString(), exportString);
		} catch (final Exception e) {
			LOGGER.error("Errore durante il download del documento", e);
			showError(e);
		}
		return sc;
	}
	
	/**
	 * Restituisce il form di ricerca elenco notifiche e conti consuntivi.
	 * 
	 * @return form ricerca elenco notifiche e conti consuntivi
	 */
	public ParamsRicercaContiConsuntiviDTO getFormContiConsuntivi() {
		return formContiConsuntivi;
	}

	/**
	 * Imposta il form ricerca elenco notifiche e conti consuntivi.
	 * 
	 * @param formContiConsuntivi
	 */
	public void setFormContiConsuntivi(ParamsRicercaContiConsuntiviDTO formContiConsuntivi) {
		this.formContiConsuntivi = formContiConsuntivi;
	}

	/**
	 * Restituisce il risultato.
	 * 
	 * @return risultato
	 */
	public StatoRicercaDTO getResult() {
		return result;
	}

	/**
	 * Imposta il risultato.
	 * 
	 * @param result
	 */
	public void setResult(StatoRicercaDTO result) {
		this.result = result;
	}

	/**
	 * Lista delle sedi estere.
	 * 
	 * @return lista sedi estere
	 */
	public List<SelectItemDTO> getSediEstere() {
		return sediEstere;
	}

	/**
	 * Imposta la lista delle sedi estere.
	 * 
	 * @param sediEstere
	 */
	public void setSediEstere(List<SelectItemDTO> sediEstere) {
		this.sediEstere = sediEstere;
	}

}

ACCENTURE/Progetto/red-main/RedWeb/WebContent/views/ricerca/closeButtonRicerca.xhtml
<ui:composition 	
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:p="http://primefaces.org/ui">

	<p:commandButton icon="fa fa-times" value="Chiudi" title="Chiudi" onclick="PF('dlgRicercaGenerica').hide();" oncomplete="onOffTreeBtnAssegnazione();" action="#{SessionBean.pulisciFormRicerca}" update="idDialogRicerche" styleClass="generic_width100 uniqueCloseButton"/>

</ui:composition>

ACCENTURE/Progetto/red-main/RedWeb/WebContent/views/ricerca/dettaglioDocumentoTabStoricoRicerca.xhtml
<ui:composition 	
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	
	<p:tab title="Storico">
		<p:tabView id="storico_DDTSR">
			<p:tab title="Visuale" rendered="#{DettaglioDocumentoRicercaBean.documentCmp.detail.showStoricoVisuale}">
				<p:panel id="timelinePanel_DDTSR">
					<div id="timeline-container-basic-DDTSR" class="imATimeline"></div>
				</p:panel>
			</p:tab>
			<p:tab title="Testuale">
				<p:panelGrid columns="1" layout="grid" styleClass="ui-panelgrid-blank centeredPanel collapseMoreInfo" cellpadding="10" columnClasses="ui-grid-col-12">
					<p:dataList value="#{DettaglioDocumentoRicercaBean.documentCmp.detail.storico}" var="row" type="unordered" styleClass="dataList generic_no_backgroundImp" >
						<p:outputLabel title="Data e ora operazione" value="#{row.dataOperazione} - #{row.tipoOperazione}" styleClass="detailValuegeneric_textBold"  /> 
						<p:panelGrid columns="1" layout="grid" styleClass="ui-panelgrid-blank centeredPanel collapseMoreInfo" cellpadding="10" columnClasses="ui-grid-col-12">
							<p:outputLabel title="Dati assegnante" value="ASSEGNANTE: #{row.ufficioAssegnante}/#{row.utenteAssegnante}" styleClass="detailValue"/> 
							<p:outputLabel title="Dati assegnatario" value="ASSEGNATARIO: #{row.ufficioAssegnatario}/#{row.utenteAssegnatario}" styleClass="detailValue"/> 
							<p:outputLabel title="Motivo assegnazione" value="MOTIVAZIONE: #{row.motivoAssegnazione}" styleClass="detailValue"/>
						</p:panelGrid>
					</p:dataList>
				</p:panelGrid>
			</p:tab>
			<p:tab title="Approvazioni" rendered="#{not empty DettaglioDocumentoRicercaBean.documentCmp.detail.approvazioni}">
				<div class="ui-g-12">
					<div id="timeline-container-basic-approvazioni-DDTSR" class="imATimeline" ></div>
				</div>
			</p:tab>
		</p:tabView>       			        
	</p:tab>
	        
</ui:composition>

ACCENTURE/Progetto/red-main/RedWeb/WebContent/views/ricerca/dlgAnnullaDocumento.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	
	<p:panel id="ricercaAnnullaDocument_RRAD" styleClass="generic_noborder generic_no_background generic_width510px" > 
		<div class="ui-g-4">
			<p:outputLabel for="idAnnullaDocumentoMessage" value="Messaggio annullamento"/>
		</div>
		
		<div class="ui-g-8 ">
			<p:inputTextarea id="idAnnullaDocumentoMessage" rows="3" maxlength="1000" styleClass="generic_input98"
				value="#{RicercaAnnullaProcedimentoBean.motivazione}"/>
		</div>
	
		<div class="ui-g-4">
			<p:outputLabel for="@next" value="Provvedimento Annullamento"  rendered="#{RicercaAnnullaProcedimentoBean.tipoProcedimentoNps}"/>
		</div>
		<div class="ui-g-8 ">
			<p:inputTextarea rows="3" maxlength="1000"  styleClass="generic_input98"
				value="#{RicercaAnnullaProcedimentoBean.provvedimento}" rendered="#{RicercaAnnullaProcedimentoBean.tipoProcedimentoNps}" />
		</div>
		<p:outputPanel class="buttonsDiv buttonsLayout">
			<p:commandButton icon="fa fa-pencil" value="Registra" action="#{RicercaAnnullaProcedimentoBean.registra()}"  oncomplete="PF('wdgAnnullaDocumento').hide()" 
				update="@form:ricercaAnnullaDocument_RRAD, @form:idTabsRisultati_RR:idRisDoc_RR, @form:idDettaglio_RR " 
				/>
			<p:commandButton icon="fa fa-times" value="Annulla" action="#{RicercaAnnullaProcedimentoBean.close()}" onclick="PF('wdgAnnullaDocumento').hide()" update="@form:ricercaAnnullaDocument_RRAD"/>
		</p:outputPanel>
		
	</p:panel>
</ui:composition>

ACCENTURE/Progetto/red-main/RedWeb/WebContent/views/ricerca/ricercaEstrattiContoUCBTab.xhtml
<ui:composition 	
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:red="http://xmlns.jcp.org/jsf/composite/custom">

	<h:form id="ricercaEstrattiContoUCBForm">
	
		<p:panelGrid id="pnlGridEstrattiContoUCB" layout="grid" columns="6" styleClass="ui-panelgrid-blank ricerca-red-documenti-form-testuale" 
			columnClasses="ui-grid-col-1, ui-grid-col-3 ui-fluid, ui-grid-col-1, ui-grid-col-3 ui-fluid, ui-grid-col-1, ui-grid-col-3 ui-fluid">
			
			<p:outputPanel>	
				<p:outputLabel value="Esercizio" styleClass="generic_textBold" />
				<p:outputLabel for="esercizio" value="*" styleClass="generic_textBold generic_redStar"/>
			</p:outputPanel>	
			<p:inputNumber id="esercizio" value="#{SessionBean.ricercaFormContainer.estrattiContoUCB.esercizio}" maxValue="9999" thousandSeparator="" padControl="false" styleClass = "obbligatorio" />
		
			<p:outputLabel value="Trimestre" styleClass="generic_textBold" />
			<p:inputNumber id="trimestre" value="#{SessionBean.ricercaFormContainer.estrattiContoUCB.trimestre}" maxValue="9" thousandSeparator="" padControl="false"/>
		
			<p:outputLabel value="Sede Estera" styleClass="generic_textBold" />
			<p:selectOneMenu style="width:220px;" id="idComboSediEstere" value="#{SessionBean.ricercaFormContainer.estrattiContoUCB.sedeEstera}" >
            	<f:selectItem itemLabel="-" itemValue="#{null}" />
            	<f:selectItems value="#{RicercaEstrattiContoCCVTBean.sediEstere}" var="sedeEstera"
            		itemLabel="#{sedeEstera.description}" itemValue="#{sedeEstera.value}" />
            </p:selectOneMenu>
		</p:panelGrid>
		
		<p:panelGrid styleClass="ui-panelgrid-blank generic_noborder generic_marginTop" columns="3" columnClasses="ui-grid-col-4 ui-fluid, ui-grid-col-4 ui-fluid, ui-grid-col-4 ui-fluid" layout="grid" >
			<p:commandButton value="Ricerca" title="Ricerca" icon="fa fa-search" action="#{SessionBean.ricercaUCB.searchEstrattiContoUCB}" />
			<p:commandButton value="Pulisci" title="Pulisci" icon="fa fa-eraser" action="#{SessionBean.ricercaUCB.pulisciRicercaEstrattiContoUCB}" styleClass="generic_nominWidth generic_width100"
				update="@parent:esercizio, @parent:trimestre, @parent:idComboSediEstere" />
			<ui:include src="closeButtonRicerca.xhtml" />
		</p:panelGrid>
	</h:form>
</ui:composition>